export const ADD_STUDENT = 'ADD_STUDENT';
export const GET_STUDENTS = 'GET_STUDENTS';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const DELETE_STUDENT_SUCCESSFUL = 'DELETE_STUDENT_SUCCESSFUL';
export const DELETE_STUDENT_ERROR = 'DELETE_STUDENT_ERROR';
export const SELECT_STUDENT = 'SELECT_STUDENT';